apiVersion: batch/v1
kind: CronJob
metadata:
  name: hpa-scaler
  namespace: default
spec:
  #schedule: "0 9,17 * * *"
  schedule: "*/1 * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-hpa
          containers:
            - name: hpa-scaler
              image: bitnami/kubectl:latest
              command: ["kubectl", "scale", "--replicas=2", "deployment/ngx-admin-deployment"]
              # ["kubectl", "get", "deployments"]
              #["kubectl", "scale", "--replicas=2", "deployment/ngx-admin-deployment"]
          restartPolicy: OnFailure
