---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cronjob-hpa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronjob-hpa
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "patch", "list", "watch", "update", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronjob-hpa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cronjob-hpa
subjects:
  - kind: ServiceAccount
    name: cronjob-hpa
    namespace: default
