kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ns-test
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "secrets", "services"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create"]

