apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-admin-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngx-admin-app
  template:
    metadata:
      labels:
        app: ngx-admin-app
    spec:
      containers:
        - name: ngx-admin-pod
          image: dockerbikram/spring-petclinic:3.2.0
          resources:
            requests:
              memory: "1500Mi"
              cpu: "200m"
            limits:
              memory: "2000Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ngx-admin-loadbalancer
spec:
  selector:
    app: ngx-admin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
