apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spring-petclinic-rs
spec:
  replicas: 4
  selector:
    ## Node the Selector
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      name: tomcat
      labels:
        pod: spring-petclinic
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: dockerbikram/spring-petclinic:3.2.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-svc
  labels:
    app: spring-petclinic
spec:
  type: NodePort
  ports:
    - port: 8080  # inside container
      targetPort: 8080
      nodePort: 31111 #expose , if dont give takes default
      protocol: TCP
  selector:
    app: spring-petclinic
