apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.4
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: REDIS_CONF
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-pvc
  updateStrategy:
    type: RollingUpdate
