apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngx-admin-nginx
  template:
    metadata:
      labels:
        app: ngx-admin-nginx
    spec:
      volumes:
        - name: ngx-admin-volume
          emptyDir: {}
      containers:
        - name: ngx-admin-pod
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ngx-admin-volume
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: git
          image: alpine/git
          command:
            - git
            - clone
            - https://github.com/jstobigdata/ngx-admin-dist.git
            - /ngx-admin-repo
          volumeMounts:
            - mountPath: /ngx-admin-repo
              name: ngx-admin-volume
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ngx-admin-loadbalancer
spec:
  selector:
    app: ngx-admin-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
