####
# git clone https://github.com/akveo/ngx-admin.git
# cd ngx-admin && yarn install
# yarn build:prod
# kubectl create configmap ngx-admin-configmap --from-file=./ngx-admin/dist
########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngx-admin-nginx
  template:
    metadata:
      labels:
        app: ngx-admin-nginx
    spec:
      volumes:
        - name: ngx-admin-volume
          configMap:
            name: ngx-admin-configmap
      containers:
        - name: ngx-admin-pod
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ngx-admin-volume
              mountPath: /usr/share/nginx/html
---
## Define the Service here
