apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-admin-deployment
spec:
  ## Ideally - remove replicas
  replicas: 1
  selector:
    matchLabels:
      app: ngx-admin-app
  template:
    metadata:
      labels:
        app: ngx-admin-app
    spec:
      containers:
        - name: ngx-admin-pod
          image: dockerbikram/ngx-admin-nginx:latest
          resources:
            requests:
              memory: "15Mi"
              cpu: "5m"
            limits:
              memory: "20Mi"
              cpu: "5.5m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ngx-admin-loadbalancer
spec:
  selector:
    app: ngx-admin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
